elections/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'elections'
urlpatterns = [
    url(r'^$', views.index, name = 'home'),
    url(r'^areas/(?P<area>[가-힣]+)/$', views.areas),
    url(r'^areas/(?P<area>[가-힣]+)/results$', views.results),
    url(r'^polls/(?P<poll_id>\d+)/$', views.polls),
    url(r'^candidates/(?P<name>[가-힣]+)/$', views.candidates),
]

leave/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'leave'
urlpatterns = [
    url(r'^leave/$', views.index, name = 'home'),
    url(r'^leave/detail/$', views.detail, name = 'detail'),
    url(r'^leave/regist/(?P<pk>\d+)/$', views.regist, name = 'regist'),
    url(r'^late/(?P<pk>\d+)/$', views.late_cal, name = 'late_cal'),
    url(r'^delete/(?P<pk>\d+)/$', views.delete, name = 'delete'),
    url(r'^edit/(?P<pk>\d+)/$', views.edit, name = 'edit'),
    url(r'^contact/$', views.contact, name = 'contact'),
]

programmers/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('elections.urls')),
    url(r'^', include('leave.urls', namespace='leave')),
    url(r'^', include('social_django.urls', namespace='social')),
]

elections/models.py
from django.db import models

# Create your models here.
class Candidate(models.Model):
    name = models.CharField(max_length=10)
    introduction = models.TextField()
    area = models.CharField(max_length=10)
    party_number = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Poll(models.Model):
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    area = models.CharField(max_length=15)

class Choice(models.Model):
    poll = models.ForeignKey('Poll', on_delete = models.CASCADE)
    candidate = models.ForeignKey('Candidate', on_delete = models.CASCADE)
    votes = models.IntegerField(default=0)

elections/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, Http404
from .models import Candidate, Poll, Choice
import datetime
from django.db.models import Sum

def index(request):
    candidates = Candidate.objects.all()
    context = {'candidates':candidates}
    return render(request, "elections/index.html", context)

def areas(request, area):
    today = datetime.datetime.now()
    try:
        polls = Poll.objects.filter(area = area, start_date__lte=today, end_date__gte=today)
        candidates = Candidate.objects.filter(area = area)
    except:
        polls = None
        candidates = None

    context = {'candidates':candidates,
    'area':area,
    'polls':polls
    }
    return render(request, "elections/area.html", context)

def polls(request, poll_id):
    poll = Poll.objects.get(pk=poll_id)
    selection = request.POST['choice']

    try:
        choice = Choice.objects.get(poll_id = poll_id, candidate_id = selection )
        choice.votes += 1
        choice.save()
    except:
        choice = Choice(poll_id = poll_id, candidate_id = selection, votes=1)
        choice.save()

    return HttpResponseRedirect("/areas/{}/results".format(poll.area))


def results(request, area):
    candidates = Candidate.objects.filter(area=area)
    polls = Poll.objects.filter(area=area)
    poll_results = []
    for poll in polls:
        result = {}
        result['start_date'] = poll.start_date
        result['end_date'] = poll.end_date
        total_votes = Choice.objects.filter(poll_id = poll.id).aggregate(Sum('votes'))
        result['total_votes'] = total_votes['votes__sum']

        rates = []
        for candidate in candidates:
            try:
                choice = Choice.objects.get(poll_id = poll.id, candidate_id = candidate.id)
                rates.append(round(choice.votes / result['total_votes'] * 100,1))
            except:
                rates.append(0)
        result['rates'] = rates
        poll_results.append(result)

    context = {
    'candidates':candidates,
    'area':area,
    'poll_results':poll_results
    }
    return render(request, "elections/results.html", context)

def candidates(request, name):
    candidate = get_object_or_404(Candidate, name=name)

    return HttpResponse(candidate.name)

elections/templates/elections/area.html
{% extends "elections/layout.html" %}

{% block title %}
지역구
{% endblock %}

{% block content %}

<div class="container">
<h1>{{ area }}</h1>
<br>
{% if polls %}

    {% for poll in polls %}
    <table class="table table-striped">
        <thead>
        <tr>
            <td><B>이름</B></td>
            <td><B>소개</B></td>
            <td><B>기호</B></td>
            <td><B>지지하기</B></td>
        </tr>
        </thead>
        <tbody>
        {% for candidate in candidates%}

        <tr>
            <td> {{ candidate.name }}</td>
            <td> {{ candidate.introduction }} </td>
            <td> 기호{{ candidate.party_number }}번 </td>
            <td>
                <form action = "/polls/{{poll.id}}/" method="post">
                  {% csrf_token %}
                    <button name="choice" value="{{candidate.id}}">선택</button>
                </form>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    {% endfor %}

    {% else %}
    여론조사가 없습니다.
    {% endif %}
{% endblock %}

elections/templates/elections/index.html
{% extends "elections/layout.html" %}

{% block title %}
선거후보
{% endblock %}

{% block content %}
<div class="container">
    <table class="table table-striped">
        <thead>
        <tr>
            <td><B>이름</B></td>
            <td><B>소개</B></td>
            <td><B>출마지역</B></td>
            <td><B>기호</B></td>
        </tr>
        </thead>
        <tbody>
        {% for candidate in candidates %}

        <tr>
            <td> {{ candidate.name }}</td>
            <td> {{ candidate.introduction }}</td>
            <td> <a href= "areas/{{ candidate.area }}/"> {{ candidate.area }} </a> </td>
            <td> {{ candidate.party_number }}</td>
        </tr>
        {% endfor %}
        <tbody>
    </table>
{% endblock %}

elections/templates/elections/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <link rel ="shortcut icon" type = "image/x-icon" href="{% static 'elections/fav.ico' %}" />
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'elections:home'%}">사이트명</a>
    </div>
</nav>
  {% block content %}{% endblock %}
</body>
</html>

elections/templates/elections/results.html
{% extends "elections/layout.html" %}

{% block title %}
{{area}} 여론조사 결과
{% endblock %}

{% block content %}

<div class="container">
<h1>{{area}}</h1>
<br>
<table class="table table-striped">
    <thead>
    <tr>
        <td><B>기간</B></td>
        {% for candidate in candidates %}
        <td><B>{{candidate.name}}</B></td>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for result in poll_results %}
    <tr>
        <td> {{result.start_date.year}}/{{result.start_date.month}}/{{result.start_date.day}}~
          {{result.end_date.year}}/{{result.end_date.month}}/{{result.end_date.day}}
        </td>
        {% for rate in result.rates %}
        <td> {{rate}}%</td>
        {% endfor %}
    </tr>
    {% endfor %}
    <tbody>
</table>
</div>
{% endblock %}