leave/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'leave'
urlpatterns = [
    url(r'^leave/$', views.index, name = 'home'),
    url(r'^leave/detail/$', views.detail, name = 'detail'),
    url(r'^leave/regist/(?P<pk>\d+)/$', views.regist, name = 'regist'),
    url(r'^late/(?P<pk>\d+)/$', views.late_cal, name = 'late_cal'),
    url(r'^delete/(?P<pk>\d+)/$', views.delete, name = 'delete'),
    url(r'^edit/(?P<pk>\d+)/$', views.edit, name = 'edit'),
    url(r'^contact/$', views.contact, name = 'contact'),
]

programmers/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('elections.urls')),
    url(r'^', include('leave.urls', namespace='leave')),
    url(r'^', include('social_django.urls', namespace='social')),
]

leave/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


TIME_CHOICES = (
    ( '오전', '오전'),
    ( '오후', '오후'),
    )

class Employee(models.Model):
    name = models.CharField(max_length=10)
    employed_date = models.DateField()
    givenLeave = models.DecimalField(default=15, max_digits=3, decimal_places=1,
    validators = [MinValueValidator(0.0), MaxValueValidator(50)])
    usedLeave = models.DecimalField(default=0, max_digits=3, decimal_places=1,
    validators = [MinValueValidator(0.0), MaxValueValidator(50)])
    leftLeave = models.DecimalField(default=0, max_digits=3, decimal_places=1,
    validators = [MinValueValidator(0.0)])
    late = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Leave(models.Model):
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE)
    startDate = models.DateField()
    startTime = models.CharField(choices=TIME_CHOICES, max_length=3)
    endDate = models.DateField()
    endTime = models.CharField(choices=TIME_CHOICES, max_length=3)
    leaveLen = models.DecimalField(default=0, max_digits=3, decimal_places=1,
    validators = [MinValueValidator(0.0)])
    briefs = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.briefs

'''
class Choice(models.Model):
    poll = models.ForeignKey('Poll', on_delete = models.CASCADE)
    candidate = models.ForeignKey('Candidate', on_delete = models.CASCADE)
    votes = models.IntegerField(default=0)
'''

leave/forms.py
from django.forms import *
from .models import *
from django.utils.translation import gettext_lazy as _

class RegistForm(ModelForm):
    class Meta:
        model = Leave
        fields = [
        'startDate',
        'startTime',
        'endDate',
        'endTime',
        'briefs']
        labels = {
        'startDate': _('시작날짜'),
        'startTime': _('시작시간'),
        'endDate': _('종료날짜'),
        'endTime': _('종료시간'),
        'briefs': _('사유')
        }
        help_texts = {
        'briefs': _('휴가 사유를 간단하게 남겨주세요')
        }
        widgets = {
            'startDate': DateInput(attrs={'class': 'dateCalendar'}),
            'endDate' : DateInput(attrs={'class': 'dateCalendar'}),
        }

class ContactForm(Form):
    subject = CharField(max_length=100)
    message = CharField()
    sender = EmailField()
    cc_myself = BooleanField(required=False)

leave/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, Http404
from .models import Employee, Leave
import datetime
from django.db.models import Sum
from .forms import *

def index(request):
    today = datetime.date.today()
    employees = Employee.objects.all()
    for employee in employees:
        gap = today - employee.employed_date
        if gap.days // 365 >= 3:
             employee.givenLeave = 15 + ((gap.days // 365 - 3) // 2 + 1)
        pk = employee.id
        leaves = Leave.objects.filter(employee_id=pk)

        sum = 0
        for leave in leaves:
            sum += leave.leaveLen
        employee.usedLeave = sum
        employee.leftLeave = employee.givenLeave - employee.usedLeave
        employee.save()

    context = {
    'employees':employees,
    }

    return render(request, "leave/index.html", context)


def detail(request):
    leaves = Leave.objects.all()
    employees = Employee.objects.all()

    for leave in leaves:
        leaveGap = leave.endDate - leave.startDate
        leave.leaveLen = leaveGap.days
        if leave.endTime == '오전' and leave.startTime == '오후':
            pass
        elif leave.endTime == '오후' and leave.startTime == '오전':
            leave.leaveLen += 1
        else:
            leave.leaveLen += 0.5

        leave.save()

    q = request.GET.get('q', '')
    if q:
        try:
            searched_employee = employees.get(name__icontains=q)
        except:
            raise Http404("올바른 검색어를 입력해주세요")
        search_key = searched_employee.id
        leaves = leaves.filter(employee_id=search_key).order_by('-updated_at')
    context = {
    'leaves':leaves,
    'q':q,
    }
    return render(request, "leave/detail.html", context)


def regist(request, pk):
    employee = Employee.objects.get(pk=pk)
    if request.method == "POST":
        form = RegistForm(request.POST)
        if form.is_valid():
            leave = form.save(commit=False)
            leave.employee = employee
            leave.save()
            return redirect('../../detail')
    else:
        form = RegistForm()

    return render(request, 'leave/regist.html', {'form': form})


def late_cal(request, pk):
    employee = Employee.objects.get(pk=pk)
    employee.late += 1
    employee.save()
    return redirect("../../leave")

def delete(request, pk):
    leave = Leave.objects.get(pk=pk)
    leave.delete()
    return redirect("../../leave/detail")

def edit(request, pk):
    leave = Leave.objects.get(pk=pk)
    if request.method == "POST":
        form = RegistForm(request.POST, instance=leave)
        if form.is_valid():
            leave = form.save(commit=False)
            leave.save()
            return redirect('../../detail')
    else:
        form = RegistForm(instance=leave)

    return render(request, 'leave/regist.html', {'form': form})


def contact(request):
    if request.method == 'Post':
        form = ContactForm(request.Post)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['rocky@cvkorea.co.kr']
            if cc_myself:
                recipients.append(sender)

            return HttpResponseRedirect('/thanks/')
    else:
        form = ContactForm()

    return render(request, 'leave/contact.html', {
        'form': form
    })

leave/templates/leave/contact.html
{% extends "leave/layout.html" %}

{% block title %}
의견 남기기
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>의견 남기기</h1>
      <blockquote>
        <p>서비스 개선을 위한 의견을 자유롭게 남겨주세요</p>
      </blockquote>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <form method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="fieldWrapper">
          {{ form.subject.errors }}
          <label for="id_subject">Email subject:</label>
          {{ form.subject }}
        </div>
        <div class="fieldWrapper">
          {{ form.message.errors }}
          <label for="id_message">Your message:</label>
          {{ form.message }}
        </div>
        <div class="fieldWrapper">
          {{ form.sender.errors }}
          <label for="id_sender">Your email address:</label>
          {{ form.sender }}
        </div>
        <div class="fieldWrapper">
          {{ form.cc_myself.errors }}
          <label for="id_cc_myself">CC yourself?</label>
          {{ form.cc_myself }}
        </div>
        <button class="btn btn-info" type="submit">보내기</button>
      </form>
      <a class="badge" href="{% url 'leave:home' %}">메인으로 돌아가기</a>

    </div>
  </div>
</div>

{% endblock %}

leave/templates/leave/detail.html
{% extends "leave/layout.html" %}

{% block title %}
개별 휴가 상세
{% endblock %}

{% block content %}
<div class="container">
  <form action='', method="get">
    <input type="text" name='q' value='{{ q }}' />
    <input type="submit" value='검색' />
  </form>
</div>

<div class="container">
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th><B>이름</B></th>
            <th><B>휴가시작일</B></th>
            <th><B>휴가종료일</B></th>
            <th><B>휴가일수</B></th>
            <th><B>적요</B></th>
            <th><B>수정 및 삭제</B></th>
        </tr>
        </thead>
        <tbody>
        {% for leave in leaves %}

        <tr>
            <td> <a class="font-weight-bold text-muted" href= "?q={{ leave.employee.name }}"> {{ leave.employee.name }} </a></td>
            <td> {{ leave.startDate.year }} / {{ leave.startDate.month }} /
              {{ leave.startDate.day }} / {{ leave.startTime }}</td>
            <td> {{ leave.endDate.year }} / {{ leave.endDate.month }} /
              {{ leave.endDate.day }} / {{ leave.endTime }} </td>
            <td> {{ leave.leaveLen }}</td>
            <td> {{ leave.briefs }}</td>
            <td>
              <a class="btn btn-warning" href = "{% url "leave:edit" leave.id %}" role="button">수정</a>
              <a class="btn btn-info" href = "{% url "leave:delete" leave.id %}" role="button">삭제</a>
            </td>
        </tr>

        {% endfor %}
        <tbody>
    </table>
{% endblock %}

leave/templates/leave/index.html
{% extends "leave/layout.html" %}

{% block title %}
컨비니언스 휴가 시스템
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12 mb-5">

      <!-- <a class="btn btn-primary" href = "{% url "social:begin" "google-oauth2" %}" role="button">로그인하기</a> -->

      <div class="alert alert-info">
        <h4>구현 내용</h4>
        <ul>
          <li>입사일 기준으로 휴가일 자동 계산하기</li>
          <li>반차 계산 자동으로 해주기</li>
        </ul>
        <br>
        <h4>구현 해야할 내용</h4>
        <ul>
          <li>주말을 자동으로 연차일에서 빼주기</li>
          <li>Ajax/jQuery 활용해서 비동기 처리 하기</li>
          <li>휴가 신청, 수정, 삭제하기</li>
          <li>지각 등록, ''지각 -> 연차' 버튼 만들기 </li>
        </ul>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th><B>이름</B></th>
            <th><B>입사일</B></th>
            <th><B>휴가일</B></th>
            <th><B>사용일</B></th>
            <th><B>잔여일</B></th>
            <th><B>이번 달 지각 일수</B></th>
            <th><B>신청버튼</B></th>
          </tr>
        </thead>
        <tbody>
          {% for employee in employees %}

          <tr>
            <td> <a class="font-weight-bold text-muted" href= "detail/?q={{ employee.name }}"> {{ employee.name }}</a></td>
            <td> {{ employee.employed_date.year}}/{{employee.employed_date.month}}/{{employee.employed_date.day}}</td>
            <td> {{ employee.givenLeave }} </td>
            <td> {{ employee.usedLeave }}</td>
            <td> {{ employee.leftLeave }}</td>
            <td> {{ employee.late }} 회</td>
            <td>
              <a class="btn btn-warning" href = "{% url "leave:late_cal" employee.id %}" role="button">지각
                신청</a>
                <a class="btn btn-info" href = "{% url "leave:regist" employee.id %}" role="button">휴가
                  신청 하기</a>
                </td>
                <!-- <td>
                <form action = "/late/{{employee.id}}/" method="post">
                {% csrf_token %}
                <button name="late" value="{{employee.late}}">지각을 연차로 만드는 마법</button>
              </form>
            </td> -->

          </tr>
          {% endfor %}
          <tbody>
          </table>
        </div>
      </div>
    </div>

    {% endblock %}

leave/templates/leave/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <link rel ="shortcut icon" type = "image/x-icon" href="{% static 'elections/fav.ico' %}" />
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="./jquery-ui-1.12.1/datepicker-ko.js"></script>
</head>


<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
    <a class="navbar-brand" href="{% url 'leave:home'%}">컨비니언스 휴가 시스템</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'leave:home' %}">Home</a>
        <a class="nav-item nav-link" href="{% url 'leave:detail' %}">상세 내역 확인하기</a>

      </div>
    </div>
  </nav>



  {% block content %}{% endblock %}
</body>
</html>

leave/templates/leave/regist.html
{% extends "leave/layout.html" %}

{% block title %}
휴가 신청하기
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-info" type="submit">저장</button>
      </form>
      <a class="badge" href="{% url 'leave:home' %}">리스트로 돌아가기</a>

    </div>
  </div>
</div>

<script type="text/javascript">
$(function(){
  $(".dateCalendar").datepicker({
    numberOfMonths: [1,2],
    changeMonth: true,
    changeYear: true,
    dateFormat: "yy-mm-dd",
    dayNames: ['일요일', '월요일', '화요일', '수요일', '목요일', '금요일', '토요일'],
    dayNamesMin: [ '일', '월', '화', '수', '목', '금', '토'],
    monthNamesShort: ['1','2','3','4','5','6','7','8','9','10','11','12'],
    monthNames: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월']
  });
});
</script>

{% endblock %}